const cardMockData =
[
  {
    "id": 1,
    "title": "The Spice Hub",
    "name": "The Spice Hub",
    "place": "Downtown",
    "minTime": 20,
    "maxTime": 30,
    "image": "https://via.placeholder.com/273x182.png?text=Spice+Hub",
    "offer": "20% OFF",
    "rating": 4.5
  },
  {
    "id": 2,
    "title": "Green Garden",
    "name": "Green Garden Restaurant",
    "place": "Uptown",
    "minTime": 15,
    "maxTime": 25,
    "image": "https://via.placeholder.com/273x182.png?text=Green+Garden",
    "offer": "Free Dessert",
    "rating": 4.2
  },
  {
    "id": 3,
    "title": "Burger Town",
    "name": "Burger Town",
    "place": "Midtown",
    "minTime": 10,
    "maxTime": 20,
    "image": "https://via.placeholder.com/273x182.png?text=Burger+Town",
    "offer": "",
    "rating": 4.0
  },
  {
    "id": 4,
    "title": "Sushi World",
    "name": "Sushi World",
    "place": "City Center",
    "minTime": 30,
    "maxTime": 40,
    "image": "https://via.placeholder.com/273x182.png?text=Sushi+World",
    "offer": "15% OFF",
    "rating": 4.7
  },
  {
    "id": 5,
    "title": "Pizza Palace",
    "name": "Pizza Palace",
    "place": "Suburb",
    "minTime": 20,
    "maxTime": 35,
    "image": "https://via.placeholder.com/273x182.png?text=Pizza+Palace",
    "offer": "Buy 1 Get 1",
    "rating": 4.3
  },
  {
    "id": 6,
    "title": "Restaurant WFQZC",
    "name": "Restaurant WFQZC",
    "place": "New City",
    "minTime": 38,
    "maxTime": 60,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+WFQZC",
    "offer": "Free Dessert",
    "rating": 3.5
  },
  {
    "id": 7,
    "title": "Restaurant TLFD5",
    "name": "Restaurant TLFD5",
    "place": "New City",
    "minTime": 10,
    "maxTime": 33,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+TLFD5",
    "offer": "Early Bird 10%",
    "rating": 4.4
  },
  {
    "id": 8,
    "title": "Restaurant 654XE",
    "name": "Restaurant 654XE",
    "place": "West End",
    "minTime": 26,
    "maxTime": 41,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+654XE",
    "offer": "",
    "rating": 4.0
  },
  {
    "id": 9,
    "title": "Restaurant W3T63",
    "name": "Restaurant W3T63",
    "place": "Midtown",
    "minTime": 28,
    "maxTime": 42,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+W3T63",
    "offer": "",
    "rating": 4.7
  },
  {
    "id": 10,
    "title": "Restaurant P03KW",
    "name": "Restaurant P03KW",
    "place": "City Center",
    "minTime": 39,
    "maxTime": 39,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+P03KW",
    "offer": "Free Dessert",
    "rating": 4.8
  },
  {
    "id": 11,
    "title": "Restaurant 4G7T8",
    "name": "Restaurant 4G7T8",
    "place": "City Center",
    "minTime": 25,
    "maxTime": 38,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+4G7T8",
    "offer": "Free Drink",
    "rating": 4.1
  },
  {
    "id": 12,
    "title": "Restaurant RSISH",
    "name": "Restaurant RSISH",
    "place": "Downtown",
    "minTime": 19,
    "maxTime": 41,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+RSISH",
    "offer": "30% OFF",
    "rating": 4.3
  },
  {
    "id": 13,
    "title": "Restaurant 5R2H1",
    "name": "Restaurant 5R2H1",
    "place": "Suburb",
    "minTime": 38,
    "maxTime": 57,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+5R2H1",
    "offer": "30% OFF",
    "rating": 3.8
  },
  {
    "id": 14,
    "title": "Restaurant HD6RT",
    "name": "Restaurant HD6RT",
    "place": "Old Town",
    "minTime": 28,
    "maxTime": 31,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+HD6RT",
    "offer": "15% OFF",
    "rating": 3.7
  },
  {
    "id": 15,
    "title": "Restaurant MO4KA",
    "name": "Restaurant MO4KA",
    "place": "Suburb",
    "minTime": 29,
    "maxTime": 56,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+MO4KA",
    "offer": "30% OFF",
    "rating": 4.4
  },
  {
    "id": 16,
    "title": "Restaurant G33AD",
    "name": "Restaurant G33AD",
    "place": "New City",
    "minTime": 30,
    "maxTime": 58,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+G33AD",
    "offer": "Free Dessert",
    "rating": 4.6
  },
  {
    "id": 17,
    "title": "Restaurant 6OUGL",
    "name": "Restaurant 6OUGL",
    "place": "Harbor",
    "minTime": 29,
    "maxTime": 49,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+6OUGL",
    "offer": "Free Drink",
    "rating": 3.7
  },
  {
    "id": 18,
    "title": "Restaurant YXOGZ",
    "name": "Place UO69",
    "place": "Midtown",
    "minTime": 26,
    "maxTime": 38,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+YXOGZ",
    "offer": "30% OFF",
    "rating": 4.1
  },
  {
    "id": 19,
    "title": "Restaurant 3TKBK",
    "name": "Place LM1I",
    "place": "Downtown",
    "minTime": 10,
    "maxTime": 50,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+3TKBK",
    "offer": "Buy 1 Get 1",
    "rating": 4.3
  },
  {
    "id": 20,
    "title": "Restaurant FK4O2",
    "name": "Restaurant FK4O2",
    "place": "City Center",
    "minTime": 24,
    "maxTime": 30,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+FK4O2",
    "offer": "Free Dessert",
    "rating": 4.0
  },
  {
    "id": 21,
    "title": "Restaurant QG056",
    "name": "Place B8N0",
    "place": "Harbor",
    "minTime": 10,
    "maxTime": 37,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+QG056",
    "offer": "Buy 1 Get 1",
    "rating": 4.3
  },
  {
    "id": 22,
    "title": "Restaurant UALLR",
    "name": "Restaurant UALLR",
    "place": "Old Town",
    "minTime": 17,
    "maxTime": 38,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+UALLR",
    "offer": "Free Drink",
    "rating": 4.4
  },
  {
    "id": 23,
    "title": "Restaurant 3PKHZ",
    "name": "Restaurant 3PKHZ",
    "place": "Suburb",
    "minTime": 37,
    "maxTime": 51,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+3PKHZ",
    "offer": "Free Dessert",
    "rating": 3.8
  },
  {
    "id": 24,
    "title": "Restaurant 0657P",
    "name": "Restaurant 0657P",
    "place": "Old Town",
    "minTime": 31,
    "maxTime": 58,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+0657P",
    "offer": "Discount 10%",
    "rating": 3.7
  },
  {
    "id": 25,
    "title": "Restaurant TOJ7D",
    "name": "Restaurant TOJ7D",
    "place": "New City",
    "minTime": 37,
    "maxTime": 53,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+TOJ7D",
    "offer": "Free Drink",
    "rating": 4.2
  },
  {
    "id": 26,
    "title": "Restaurant 5RN36",
    "name": "Restaurant 5RN36",
    "place": "New City",
    "minTime": 26,
    "maxTime": 36,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+5RN36",
    "offer": "20% OFF",
    "rating": 4.4
  },
  {
    "id": 27,
    "title": "Restaurant V7DS0",
    "name": "Restaurant V7DS0",
    "place": "Central Park",
    "minTime": 25,
    "maxTime": 37,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+V7DS0",
    "offer": "",
    "rating": 4.9
  },
  {
    "id": 28,
    "title": "Restaurant FNSFB",
    "name": "Restaurant FNSFB",
    "place": "City Center",
    "minTime": 37,
    "maxTime": 39,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+FNSFB",
    "offer": "Discount 10%",
    "rating": 4.4
  },
  {
    "id": 29,
    "title": "Restaurant WNY8B",
    "name": "Restaurant WNY8B",
    "place": "Suburb",
    "minTime": 32,
    "maxTime": 51,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+WNY8B",
    "offer": "",
    "rating": 4.4
  },
  {
    "id": 30,
    "title": "Restaurant Z2DFT",
    "name": "Restaurant Z2DFT",
    "place": "Harbor",
    "minTime": 34,
    "maxTime": 47,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+Z2DFT",
    "offer": "30% OFF",
    "rating": 5.0
  },
  {
    "id": 31,
    "title": "Restaurant U5V22",
    "name": "Restaurant U5V22",
    "place": "Central Park",
    "minTime": 39,
    "maxTime": 40,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+U5V22",
    "offer": "Free Drink",
    "rating": 4.8
  },
  {
    "id": 32,
    "title": "Restaurant ITGLD",
    "name": "Place MBHV",
    "place": "Central Park",
    "minTime": 23,
    "maxTime": 51,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+ITGLD",
    "offer": "Special Combo",
    "rating": 3.8
  },
  {
    "id": 33,
    "title": "Restaurant NCHZT",
    "name": "Restaurant NCHZT",
    "place": "Central Park",
    "minTime": 16,
    "maxTime": 54,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+NCHZT",
    "offer": "Buy 1 Get 1",
    "rating": 3.6
  },
  {
    "id": 34,
    "title": "Restaurant Y44E3",
    "name": "Restaurant Y44E3",
    "place": "Suburb",
    "minTime": 21,
    "maxTime": 41,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+Y44E3",
    "offer": "",
    "rating": 4.6
  },
  {
    "id": 35,
    "title": "Restaurant 7OVWR",
    "name": "Restaurant 7OVWR",
    "place": "Downtown",
    "minTime": 13,
    "maxTime": 49,
    "image": "https://via.placeholder.com/273x182.png?text=Restaurant+7OVWR",
    "offer": "Free Dessert",
    "rating": 3.8
  }
]

export default cardMockData;